# serverless.yml
service: tickets
custom:
  tableName: "tickets-table-${self:provider.stage}"
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
      - prod
plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["TicketsTable", "Arn"] }
  environment:
    TICKETS_TABLE: ${self:custom.tableName}
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
resources:
  Resources:
    TicketsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI-1
            AttributeType: S
          - AttributeName: GSI-2
            AttributeType: S
          - AttributeName: GSI-3
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 20
          WriteCapacityUnits: 20
        TableName: ${self:custom.tableName}
        GlobalSecondaryIndexes:
          - IndexName: GSI-1
            KeySchema:
              - AttributeName: GSI-1
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: GSI-2
            KeySchema:
              - AttributeName: GSI-2
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: GSI-3
            KeySchema:
              - AttributeName: GSI-3
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
