version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    executor:
      name: node/default
      tag: '14.14'
    steps:
      - checkout
      - node/install-packages
      - run:
         command: npm install serverless
      - run:        
          command: npm run test-circleci  

workflows:
  test:
    jobs:
      - test