version: '2.1'
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages
      - run:
         command: npm install -g serverless
      - run:        
          command: npm run test-ci  

workflows:
  test_my_app:
    jobs:
      - test